# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'UnidaysSampleApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'UnidaysVerificationSDK', '0.2.0'
  # Pods for UnidaysSampleApp

end
